name: Runner

options:
  bundleIdPrefix: ""
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en
  knownRegions:
    - Base
    - ko
    - en

configs:
  Debug: debug
  Profile: none
  Release: release
  Debug-dev: debug
  Profile-dev: none
  Release-dev: release
  Debug-prod: debug
  Profile-prod: none
  Release-prod: release

settings:
  base:
    ALWAYS_SEARCH_USER_PATHS: NO
    CLANG_ANALYZER_NONNULL: YES
    CLANG_CXX_LANGUAGE_STANDARD: "gnu++0x"
    CLANG_ENABLE_MODULES: YES
    CLANG_ENABLE_OBJC_ARC: YES
    CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
    CLANG_WARN_BOOL_CONVERSION: YES
    CLANG_WARN_COMMA: YES
    CLANG_WARN_CONSTANT_CONVERSION: YES
    CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
    CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
    CLANG_WARN_EMPTY_BODY: YES
    CLANG_WARN_ENUM_CONVERSION: YES
    CLANG_WARN_INFINITE_RECURSION: YES
    CLANG_WARN_INT_CONVERSION: YES
    CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
    CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
    CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
    CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
    CLANG_WARN_STRICT_PROTOTYPES: YES
    CLANG_WARN_SUSPICIOUS_MOVE: YES
    CLANG_WARN_UNREACHABLE_CODE: YES
    CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
    ENABLE_STRICT_OBJC_MSGSEND: YES
    ENABLE_TESTABILITY: YES
    GCC_NO_COMMON_BLOCKS: YES
    GCC_WARN_64_TO_32_BIT_CONVERSION: YES
    GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
    GCC_WARN_UNDECLARED_SELECTOR: YES
    GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
    GCC_WARN_UNUSED_FUNCTION: YES
    GCC_WARN_UNUSED_VARIABLE: YES
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    SDKROOT: iphoneos
  configs:
    Debug:
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      ONLY_ACTIVE_ARCH: YES
      GCC_DYNAMIC_NO_PIC: NO
      GCC_PREPROCESSOR_DEFINITIONS: 'DEBUG=1 $(inherited)'
    Release:
      MTL_ENABLE_DEBUG_INFO: "NO"
      SWIFT_COMPILATION_MODE: wholemodule
      VALIDATE_PRODUCT: YES
      COPY_PHASE_STRIP: "NO"

targets:
  Runner:
    type: application
    platform: iOS

    configFiles:
      Debug: Flutter/Debug.xcconfig
      Release: Flutter/Release.xcconfig
      Profile: Flutter/Release.xcconfig
      Debug-dev: Flutter/Debug-dev.xcconfig
      Release-dev: Flutter/Release-dev.xcconfig
      Profile-dev: Flutter/Profile-dev.xcconfig
      Debug-prod: Flutter/Debug-prod.xcconfig
      Release-prod: Flutter/Release-prod.xcconfig
      Profile-prod: Flutter/Profile-prod.xcconfig

    sources:
      - path: Runner
      - path: Flutter

    preBuildScripts:
      - name: Run Script
        path: xcodegen/script/run_script.sh
        basedOnDependencyAnalysis: false

    postBuildScripts:
      - name: Thin Binary
        path: xcodegen/script/thin_binary.sh
        basedOnDependencyAnalysis: false
        inputFiles:
          - ${TARGET_BUILD_DIR}/${INFOPLIST_PATH}

    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: "NO"
        CLANG_ENABLE_MODULES: YES
        CURRENT_PROJECT_VERSION: "$(FLUTTER_BUILD_NUMBER)"
        ENABLE_BITCODE: "NO"
        INFOPLIST_FILE: Runner/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: ""
        PRODUCT_NAME: "$(TARGET_NAME)"
        SWIFT_OBJC_BRIDGING_HEADER: Runner/Runner-Bridging-Header.h
        SWIFT_VERSION: 5.0
        VERSIONING_SYSTEM: apple-generic
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Debug-dev:
          PRODUCT_BUNDLE_IDENTIFIER: studio.etch.test.dev
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-dev
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release-dev:
          PRODUCT_BUNDLE_IDENTIFIER: studio.etch.test.dev
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-dev
        Profile-dev:
          PRODUCT_BUNDLE_IDENTIFIER: studio.etch.test.dev
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-dev
        Debug-prod:
          PRODUCT_BUNDLE_IDENTIFIER: studio.etch.test
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-prod
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release-prod:
          PRODUCT_BUNDLE_IDENTIFIER: studio.etch.test
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-prod
        Profile-prod:
          PRODUCT_BUNDLE_IDENTIFIER: studio.etch.test
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon-prod

  RunnerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RunnerTests
    dependencies:
      - target: Runner
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: 1.0
        SWIFT_VERSION: 5.0
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Runner.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Runner"


schemes:
  Runner:
    build:
      targets:
        Runner: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Profile
    analyze:
      config: Debug
    archive:
      config: Release
  dev:
    build:
      targets:
        Runner: all
    run:
      config: Debug-dev
    test:
      config: Debug-dev
    profile:
      config: Profile-dev
    analyze:
      config: Debug-dev
    archive:
      config: Release-dev
  prod:
    build:
      targets:
        Runner: all
    run:
      config: Debug-prod
    test:
      config: Debug-prod
    profile:
      config: Profile-prod
    analyze:
      config: Debug-prod
    archive:
      config: Release-prod
